service: serverless-image-processor

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

functions:
  processImage:
    handler: handler.processImage
    events:
      - http:
          path: process-image/{bucket}/{file}
          method: get

custom:
  apigwBinary:
    types:
      - '*/*'
