service: serverless-image-processor

plugins:
  - serverless-apigw-binary

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  apiKeys:
    - cloudFrontKey

functions:
  processImage:
    handler: handler.processImage
    events:
      - http:
          path: /{bucket}/process-image/{file}
          method: get
          private: true

custom:
  apigwBinary:
    types:
      - '*/*'
